### ISSUE TITLE
grad can be implicitly created only for scalar outputs

### ISSUE THREAD

**Issue by tiantianbukuaile** [MrChenFeng/Adaptive-Soft-Contrastive-Learning_ICPR2022#2]
Hello, when I set the model to byol in the code, an error is reported“RuntimeError: grad can be implicitly created only for scalar outputs‘, When using the byol model, the loss is not a scalar, how can I solve it? Is it necessary to summ?

**Comment by MrChenFeng** [comment]
Hi, I will check this after neurips ddl.
